# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9sS22fzqo2Q5vJmDoumeRr_cf973pai
"""

def encryption(s, key):
    output = ""
    for char in s:
        if char.isalpha():  # Check if the character is alphabetic
            shifted = chr(ord(char) + key)  # Shift the character by the key value
            if char.islower() and shifted > 'z':  # Check if the character is lowercase and needs wrapping
                shifted = chr(ord(shifted) - 26)  # Wrap around the alphabet if necessary
            elif char.isupper() and shifted > 'Z':  # Check if the character is uppercase and needs wrapping
                shifted = chr(ord(shifted) - 26)  # Wrap around the alphabet if necessary
            output += shifted  # Append the shifted character to the output
        else:
            output += char  # Keep non-alphabetic characters unchanged
    return output  # Return the encrypted text

def decryption(s, key):
    output = ""
    for char in s:
        if char.isalpha():  # Check if the character is alphabetic
            shifted = chr(ord(char) - key)  # Shift the character back by the key value to decrypt
            if char.islower() and shifted < 'a':  # Check if the character is lowercase and needs wrapping
                shifted = chr(ord(shifted) + 26)  # Wrap around the alphabet if necessary
            elif char.isupper() and shifted < 'A':  # Check if the character is uppercase and needs wrapping
                shifted = chr(ord(shifted) + 26)  # Wrap around the alphabet if necessary
            output += shifted  # Append the shifted character to the output
        else:
            output += char  # Keep non-alphabetic characters unchanged
    return output  # Return the decrypted text

def main():
    input_user = input("Press 'E' for encryption and 'D' for decryption: ")  # Prompt the user to choose encryption or decryption
    input_text = input("Enter text: ")  # Prompt the user to enter the text
    key = int(input("Enter key: "))  # Prompt the user to enter the encryption/decryption key

    if input_user.lower() == 'e':  # Perform encryption if the user chooses 'E' or 'e'
        print("Encrypted text:")
        print(encryption(input_text, key))  # Encrypt the input text
    elif input_user.lower() == 'd':  # Perform decryption if the user chooses 'D' or 'd'
        print("Decrypted text:")
        print(decryption(input_text, key))  # Decrypt the input text
    else:
        print("Invalid input")  # Display error message for invalid input

if __name__ == "__main__":
    main()